{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "skimasque-gateway.fullname" . }}
  labels: {{- include "skimasque-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "skimasque-gateway.selectorLabels" . | nindent 6 }}
{{- end }}
{{- if and .Values.audit.enabled .Values.audit.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skimasque-gateway.fullname" . }}-audit
  labels: {{- include "skimasque-gateway.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.audit.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.audit.persistence.size }}
{{- end }}
{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "skimasque-gateway.fullname" . }}
  labels:
    {{- include "skimasque-gateway.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels: {{- include "skimasque-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
